# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a99efb338eedb1ec1fa8f8262a880165"
application_url = "https://watched-using-vulnerability-any.trycloudflare.com"
embedded = true
name = "harshapp"
handle = "harshapp"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[app_proxy]
url = "https://watched-using-vulnerability-any.trycloudflare.com"
subpath = "icona"
prefix = "apps"

[auth]
redirect_urls = [
  "https://watched-using-vulnerability-any.trycloudflare.com/auth/callback",
  "https://watched-using-vulnerability-any.trycloudflare.com/auth/shopify/callback",
  "https://watched-using-vulnerability-any.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-eng-hr.myshopify.com"
automatically_update_urls_on_dev = true
